version: 2.1
jobs:

  test:
    working_directory: ~/ci
    docker:
      # Primary container image where all steps run.
      - image: district0x/cljs-dev:latest
    steps:
      - checkout
      - restore_cache:
          name: Restore npm package cache
          keys:
            - npm-packages-{{ checksum "package-lock.json" }}
      - run:
          name: Install node modules
          command: lein npm install
      - save_cache:
          name: Save npm package cache
          key: npm-packages-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules/
      - run: lein doo chrome-headless "browser-tests" once

  deploy:
   machine: true
   steps:
     - checkout
     - run:
         name: Deploy to clojars
         command: lein release :patch

workflows:
  version: 2
  test_and_deploy:
    jobs:
      - test
      - deploy:
          requires:
            - test
          filters:
            branches:
              only: master
